### ISSUE TITLE
wrong electrodes

### ISSUE THREAD

**Issue by MarcusWolschon** [OpenBCI/ultracortex#1]
This doesn't look anywhere near like the electrodes that came with the OpenBCI V3 and there is no part list telling users to get any other ones.
Something doesn't match up here.

**Comment by conorrussomanno** [comment]
Marcus,

Sorry for the confusion. The electrodes seen in the photos here are dry electrodes from Florida Research Instruments (FRI), found here: http://fri-fl-shop.com/product/package-of-15-disposable-reusable-dry-electrodes-and-10-disposablereusable-eeg-cup-electrodes-and-5-leads-red-white-green-black-brown/

Conor

**Comment by MarcusWolschon** [comment]
That info should get into readme.md, not into this ticket.

**Comment by conorrussomanno** [comment]
Check the readme.md.
