### ISSUE TITLE
Can anyone recommend a print-on demand service?

### ISSUE THREAD

**Issue by neuropil** [OpenBCI/ultracortex#14]
With a reasonable cost. 3D systems quoted ~4K.

Thanks!

**Comment by pattonsgirl** [comment]
Try Shapeways and i.materialize

**Comment by Tweakmind** [comment]
I recommend finding someone on 3DHubs.com

**Comment by teonbrooks** [comment]
@neuropil where are you based? IIRC @conorrussomanno mentioned that there is a service in NYC where you send them your file and one of the printing partners prints it and you can go pick it up. I am also think OpenBCI is within that network
