### ISSUE TITLE
Nova README, SRB1 -> SRB2

### ISSUE THREAD

**Issue by wjcroft** [OpenBCI/ultracortex#15]
Conor, Joel and team, great tutorial and design evolutions!

Minor typo, isn't the SRB pin closest to the board SRB2 and not SRB1 as stated in the README? It is clear from the photos that the pins closest to the board are used. But some other documentation, for example various places on the forum, shows reference on SRB2.

Cheers, William

**Comment by teonbrooks** [comment]
cc: @conorrussomanno

**Comment by gabrielibagon** [comment]
You are right! Edited "SRB1" to "SRB2" (bottom pin). This typo existed in the Mark 3 (original) documentation as well, so it's fixed there too. Thanks!
