### ISSUE TITLE
BOARD_HOLDER and BOARD_COVER stl download link for "Nova" headset CANNOT BE FOUND

### ISSUE THREAD

**Issue by wudixiaoxiami** [OpenBCI/ultracortex#17]
Hi all,
I encountered an issue on opening stl download link for board holder and cover of 'Nova' headset.

Can anyone post it again ?

Thank you very much.

Yuliang

**Comment by gabrielibagon** [comment]
Hi Yuliang,

I fixed the links for both board holder and cover in the readme, so they should work now. Thanks for catching that! 

Just for reference, there's a directory in the Ultracortex repo where you can download the stl files: https://github.com/OpenBCI/Ultracortex/tree/master/Mark_III_Nova/STLs

Gabe
