### ISSUE TITLE
QUADSTAR won't fit over OCTARING

### ISSUE THREAD

**Issue by alepirolo** [OpenBCI/ultracortex#18]
In the README.md is written "Take your QUADSTAR and stretch it so that it fits over the OCTARING" but we couldn't do it.
We tried by printing QUADSTAR bigger of 4% and of 5% but with this enlargment the OCTARING won't fit.
Can anyone explain how they managed to do this tricky part? Thank you

**Comment by onyedikilo** [comment]
Quadstar should be printed with a flexible material such as ninja flex, so that you can pull and stretch it to fit the octaring, no need to print it bigger.
