### ISSUE TITLE
MARK IV - Medium and Large STL

### ISSUE THREAD

**Issue by jspenc72** [OpenBCI/ultracortex#19]
Can you post the stl for the medium and larger versions of the MARK IV?

**Comment by nielsswinkels** [comment]
Any news here? We just received our package so I would like to print the Mark IV, but with my big head printing the small size seems pointless.

**Comment by andreaortuno** [comment]
You can find all the files on the assembly guide:

**Comment by andreaortuno** [comment]
You can find all the files on the assembly guide:
https://github.com/OpenBCI/Docs/blob/master/Headware/01-Ultracortex-Mark-IV.md
