### ISSUE TITLE
possible corrosion problem observed when using recommended parts

### ISSUE THREAD

**Issue by Abraxas3d** [OpenBCI/ultracortex#21]
Using the parts listed for https://github.com/OpenBCI/Ultracortex/tree/master/Mark_III_Nova_REVISED, I observed the following.

There seems to be some sort of reaction or corrosion when putting together the electrodes and the machine screws. 

The photos (attached below) show an electrode as it comes out of the plastic shipping bag beside electrodes that have been assembled into their pods. 

The assembled pieces were put together 24 hours ago. One can observe what appears to be corrosion between the head of the screw and the electrode. 

They were not exposed to water. They were not screwed together very tightly. Electrical conductivity has not yet been affected, but if it continues, enough corrosion could prevent signals from conducting through the wire or being picked up at all. 

These are parts ordered directly off the links in the list on github. There were no substitutions. I did not use different parts. 

So... what's going on here? I shouldn't be seeing any corrosion between these parts, right? 

This is being built for a hackfest that will be held next week (10-11 September 2016)
https://sites.google.com/site/ieeebcihackathon/

![possiblecorrosionproblem-1705](https://cloud.githubusercontent.com/assets/6608613/18233324/cc9b098c-7298-11e6-8c2e-eff2b78b5f2e.jpg)
![possiblecorrosionproblem-1708](https://cloud.githubusercontent.com/assets/6608613/18233327/cc9cf094-7298-11e6-9485-7fc69cdeefb7.jpg)
![possiblecorrosionproblem-1709](https://cloud.githubusercontent.com/assets/6608613/18233325/cc9d1556-7298-11e6-8c67-47ae7e5fd21a.jpg)
![possiblecorrosionproblem-1714](https://cloud.githubusercontent.com/assets/6608613/18233326/cc9d21f4-7298-11e6-8183-3149ea8a7bf0.jpg)

**Comment by wjcroft** [comment]
See related forum post below, showing similar coloration changes. We suggest there to remove any possible oil or other coating from your bolts.

http://openbci.com/forum/index.php?p=/discussion/885/florida-research-dry-electrodes-corrosion-reaction-discoloration
