### ISSUE TITLE
Gold Cup Electrodes - not long enough for forehead electrodes

### ISSUE THREAD

**Issue by Abraxas3d** [OpenBCI/ultracortex#22]
Even when cutting off the no-touch connectors at their base, which gives the maximum length of the Gold Cup Electrodes wires, the length of the wire is simply not long enough to reach the forehead electrodes. 

I have a wire with the right connectors to make an extension for my build, but if someone tried to build this and didn't have that, it would be annoying. 

Has someone actually used these wires in constructing a headset? Have a photo? Maybe the Gold Cup Electrodes wires are shorter now than when they were specified? This is with a medium sized headset, so the problem would probably be worse for a large.

**Comment by onyedikilo** [comment]
The Gold Cup Electrode wires I received with 16 channel kit is 100cm in length.  No-touch connectors are 35cm in length.
