### ISSUE TITLE
Please update the repo with instructions for printing the mark IV

### ISSUE THREAD

**Issue by jspenc72** [OpenBCI/ultracortex#26]
Current instructions indicate that the model must be scaled before printing. I have tried printing per the instructions however the hardware does not fit. 

Please update repo with properly scaled stl files that don't require any modification and are ready to print. Please also add instructions with pictures detailing the assembly process for the mark IV.

**Comment by andreaortuno** [comment]
The instructions or on our docs repo. Here is the link: https://github.com/OpenBCI/Docs/blob/master/Headware/01-Ultracortex-Mark-IV.md
