### ISSUE TITLE
Electrodes on the pictures

### ISSUE THREAD

**Issue by LeBovin** [OpenBCI/ultracortex#31]
Hey,

I would like to know if there is a tutorial to make the electrodes we can see on the Ultracortex IV's pictures ?

Thanks!

**Comment by ThreeForm** [comment]
LeBovin,
There currently is no Mark IV  electrode tutorial because the Mark IV uses
crimped connections for reliability. Electrodes that can be produced
manually would require a design change, but that will happen if enough
people ask for it.
Best,
 -Aaron

**Comment by LeBovin** [comment]
In this case, where could I buy the electrodes we can see in the pictures?

Thanks for you answer !
